default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aws_ses_domain_development

test:
  <<: *default
  database: aws_ses_domain_test

production:
  <<: *default
  database: aws_ses_domain_production
  username: aws_ses_domain
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
